Development add subcommands
threefoldtecharchive/gridify pull request #9
Opened 2023-02-16 10:59 UTC by rawdaGastan

### Related Issues

- https://github.com/rawdaGastan/gridify/issues/3
- https://github.com/rawdaGastan/gridify/issues/1
- https://github.com/rawdaGastan/gridify/issues/4
- https://github.com/rawdaGastan/gridify/issues/5
- https://github.com/rawdaGastan/gridify/issues/6

2023-02-20 15:52 UTC, rawdaGastan reviewed
Great work 💯 I left some small comments :D

2023-02-20 15:52 UTC, rawdaGastan commented on Dockerfile
> +RUN apk add --update nodejs npm
we need to add docker file in a separate dir as it not the dockerfile of gridify

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/flags.go
> +package cmd
we need to remove flags and use a file for each command separately
suggestion: cobra

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/login.go
> +	_, err := deployer.NewDeployer(mnemonics, network, showLogs)
we need to take mnemonics and network as an input from user

2023-02-20 15:52 UTC, rawdaGastan commented on init.sh
> +ginit start -f ./Procfile -e ./.env
we need to add this file in a separate dir with the dockefile

2023-02-20 15:52 UTC, rawdaGastan commented on internal/config/config.go
> +	configFile, err := os.Create(path)
what if the flle is created before?

2023-02-20 15:52 UTC, rawdaGastan commented on internal/config/config.go
> +		return errors.Wrapf(err, "could not wirte configuration data to file %s", configFile.Name())
wirte -> write

2023-02-20 15:52 UTC, rawdaGastan commented on internal/config/config.go
> +	config := Config{}
we can write it `var config Config`

2023-02-20 15:52 UTC, rawdaGastan commented on internal/config/config.go
> +		return errors.Wrap(err, "could not get user configuration directory")
I think we display the error to the user, then we should remove user

2023-02-20 15:52 UTC, rawdaGastan commented on internal/config/config.go
> +		return Config{}, errors.Wrap(err, "could not get user configuration directory")
I think we display the error to the user, then we should remove user

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/deploy.go
> +	deployer, err := deployer.NewDeployer(config.Mnemonics, config.Network, showLogs)
we can globally set log level
`zerolog.SetGlobalLevel(zerolog.DebugLevel)`
no need to pass showLogs to deployer 
also, we need to create the logger first then pass it to the deployer

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/deploy.go
> +func deploy(ports string, showLogs bool) error {
showLogs can be debug

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/deploy.go
> +	projectName, _, found := strings.Cut(splitURL[len(splitURL)-1], ".git")
I think we can get project name inside deploy function instead of passing it.

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/deploy.go
> +	fmt.Println("Project Deployed!")
here we can use logger info level, also in line 41

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +		CRU:       2,
we can also set farm id with 1

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	if len(nodes) == 0 {
we return error if no nodes found in filter. no need to check it again

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	networkName := fmt.Sprintf("gnet%s", randomString)
I thibk we can make a constrcutNetwork and add it to it
then we deploy outside function

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	vmName := fmt.Sprintf("gvm%s", randomString)
same as network

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +		err := d.deployGateway(ctx, backend, projectName, subdomain, nodes[0])
same as network

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	d.logger.Info().Msgf("getting contracts for project %s", projectName)
we can make it cancelling/destroying

2023-02-20 15:52 UTC, rawdaGastan commented on cmd/destroy.go
> +// Package cmd for handling command line arguments
same as deploy

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/workloads.go
> +		CPU:        2,
I think we shouldn't make constant values inside the functions. please check all

2023-02-20 15:52 UTC, rawdaGastan commented on internal/deployer/workloads.go
> +	dl := workloads.NewDeployment(vm.Name, 2, projectName, nil, networkName, nil, nil, []workloads.VM{vm}, nil)
node here is constant and not taken from function

2023-02-21 14:10 UTC, rawdaGastan commented on README.md
> +go build .
we can also add make build

2023-02-21 14:10 UTC, rawdaGastan commented on README.md
> +gridify deploy --ports 80,8080
make `80,8080` <ports> then explain how to write them and put an example 80,8080

2023-02-21 14:10 UTC, rawdaGastan commented on README.md
> +- go 1.18
I think we should use 1.19 as it is the latest

2023-02-21 14:10 UTC, rawdaGastan commented on README.md
> +- caddy
add release workflow and how to release
add how to test

2023-02-21 14:10 UTC, rawdaGastan commented on cmd/deploy.go
> +			fmt.Fprintln(os.Stderr, err)
use zerolog logger instead of fmt for all

2023-02-21 14:10 UTC, rawdaGastan commented on cmd/deploy.go
> +		}
we can return instead  of os.Exit(1) for all

2023-02-21 14:10 UTC, rawdaGastan commented on cmd/login.go
> +		_, err = gridDeployer.NewTFPluginClient(mnemonics, "sr25519", network, "", "", "", true, false)
why we are creating a new plugin we can only validate network and mnemonic
use: https://pkg.go.dev/github.com/bernix/cosmos-key-sign/cosmos/bip39#IsMnemonicValid

2023-02-21 14:10 UTC, rawdaGastan commented on image/Dockerfile
> +ENTRYPOINT [ "/init.sh" ]
add a line in the end :DD

2023-02-21 14:10 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	contractsSlice := make([]graphql.Contract, 0)
we can start directly with contractsSlice := contracts.NameContracts

2023-02-21 14:10 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	// TODO: cancel each contract in a separate goroutine
cancelling contracts in the same time will fail let's discuss  if batch helps.

2023-02-21 14:10 UTC, rawdaGastan commented on internal/deployer/project.go
> +// Package deployer for project deployment
set getProject name on deployer struct and remoce this file

2023-02-21 14:10 UTC, rawdaGastan commented on internal/deployer/deployer.go
> +	node := uint32(nodes[0].NodeID)
what about creating a function called findNode for example?

2023-02-21 14:16 UTC, rawdaGastan commented on internal/deployer/workloads.go
> +package deployer
we can rename it to builder.. constructor...

2023-02-21 14:28 UTC, rawdaGastan reviewed
add a check if user is logged in or not before destroy and deploy

2023-02-21 16:23 UTC, xmonader commented on README.md
> +## Build
build info should be in the very bottom, here should be how to download the latest and use

2023-02-21 16:24 UTC, xmonader commented on README.md
> +A tool used to deploy projects using threefold grid 3.
remove the 3 and link to threefold.io please

2023-02-21 16:26 UTC, xmonader requested changes

2023-02-21 16:26 UTC, xmonader commented on README.md
> +- gridify uses [ginit](https://github.com/rawdaGastan/ginit) so `.Procfile` and `.env` must exist in root directory of your project
Procfile not `.Procfile` and immediately link to a demo project structure

2023-02-21 16:26 UTC, xmonader commented on README.md
> +First [Build](#build) gridify then move the binary to any of $PATH directories, for example:
`$PATH`

2023-02-21 16:26 UTC, xmonader commented on README.md
> +Login using your mnemonics and specify which grid network to deploy on by running:
link to what mnemonics are and how to create account

2023-02-21 16:28 UTC, xmonader commented on README.md
> +Login using your mnemonics and specify which grid network to deploy on by running:
same for grid networks

2023-02-21 16:29 UTC, xmonader commented on README.md
> +ports are your services' ports defined in procfile
procfile -> Procfile

2023-02-21 16:29 UTC, xmonader commented on README.md
> +gridify generates a unique domain for each port.
for each service

2023-02-21 16:29 UTC, xmonader commented on README.md
> +To destroy deployed projects run:
is that all of the projects or the project in the current directory?

2023-02-21 16:30 UTC, xmonader commented on README.md
> +
Write a one-liner or two about this Demo and make the section heading `Gridify Demo Project`

2023-02-21 16:31 UTC, xmonader commented on README.md
> +
Add a section about how it works from a very highlevel point of view, e.g starting a virtual machine with a specific image (link to the image)

2023-02-21 16:32 UTC, xmonader commented on README.md
> +## Testing
Add a developer guide, where you have all of the toolings configured in the make in `wiki/` or `docs` directory

2023-02-21 16:32 UTC, xmonader commented on README.md
> +Run:
Explain what kind of tests running here, are these unittests, or integration tests or both or is there a specific tag to invoke .. etc (or have that fully described in the devdoc)

2023-02-21 16:33 UTC, xmonader commented on image/Dockerfile
> +RUN caddy start
Why?

2023-02-21 16:34 UTC, xmonader commented on internal/config/config.go
> +func SaveConfigData(mnemonics, network string) error {
Should be a method on the Config receiver if needed

2023-02-21 16:34 UTC, xmonader commented on internal/config/config.go
> +		return errors.Wrap(err, "could not get configuration directory")
add the configDir to the error message

2023-02-21 16:35 UTC, xmonader commented on README.md
> +## Usage
Also add a section about the configurations where they're saved on the filesystem.

2023-02-21 16:36 UTC, xmonader commented on internal/config/config.go
> +func LoadConfigData() (Config, error) {
Should be on the receiver and parameterized in the config file, make it pure to be easily tested and add another function for the side effect

2023-02-21 16:37 UTC, xmonader commented on internal/config/config.go
> +		return Config{}, errors.Wrap(err, "could not get configuration directory")
include the configDir in the error message

2023-02-21 16:39 UTC, xmonader commented on internal/deployer/random.go
> +func randString(n int) string {
What is this function used for? is it for a gateway domain prefix? if so make it more explicit please

2023-02-21 16:44 UTC, xmonader commented on internal/deployer/builder.go
> +	freeMRU := uint64(2)
please make sure the constants are usable at least between the VM specs and the node filters

2023-02-21 16:45 UTC, xmonader commented on internal/deployer/builder.go
> +	freeHRU := uint64(5)
same as above

2023-02-21 16:45 UTC, xmonader commented on internal/deployer/builder.go
> +	freeIPs := uint64(1)
samve as above

2023-02-21 16:45 UTC, xmonader commented on internal/deployer/builder.go
> +		return 0, errors.New("no node with free resources available")
add the resources request to the message please

2023-02-21 16:51 UTC, xmonader commented on internal/deployer/builder.go
> +func constructNetwork(projectName string, node uint32) workloads.ZNet {
can be 
type Builder struct { 
    projectName 
    node ..
    ....

}

then https://refactoring.guru/design-patterns/builder/go/example

2023-02-21 16:52 UTC, xmonader commented on internal/deployer/deployer.go
> +	d.logger.Info().Msg("deploying vm")
a vm

2023-02-21 16:54 UTC, xmonader commented on internal/deployer/deployer.go
> +	FQDNs := make(map[uint]string, 0)
what is the point of the length hint here, if anything you can pass the number of the services "ports" needed ahead of time, and it's not guaranteed to happen, it's a minor optimization (if and only if you know the number of keys of that map) that shouldn't be handled at this stage

2023-02-21 16:54 UTC, xmonader commented on internal/deployer/deployer.go
> +	d.logger.Info().Msg("Project Deployed!")
please be consistent with lowercase debugging messages

2023-02-21 16:58 UTC, xmonader commented on internal/deployer/builder.go
> +		FarmIDs: []uint64{1},
are we farm 1 on all networks? dev,qa,test,main? should we use FarmName instead?

2023-02-21 17:00 UTC, xmonader commented on internal/deployer/deployer.go
> +	rand.Seed(time.Now().UnixNano())
shouldn't that go in the project init?

2023-02-21 17:02 UTC, xmonader commented on main.go
> +	cmd.Execute()
should be 
if err = cmd.Execute() ; err!=nil {
    os.Exit() or fatal log it
}

2023-02-21 17:03 UTC, xmonader commented on cmd/login.go
> +	Short: "Login with mnemonics on a grid network",
on -> to

2023-02-21 17:06 UTC, xmonader commented on cmd/login.go
> +		scanner := bufio.NewReader(os.Stdin)
move the body into a function in `internal/cmd/login` and call it here

2023-02-21 17:06 UTC, xmonader commented on main.go
> +	cmd.Execute()
mark it as resolved as this was generated by cobra

2023-02-21 17:08 UTC, xmonader commented on cmd/login.go
> +		err = config.SaveConfigData(mnemonics, network)
add a note it was properly configured and saved to the user

2023-02-21 17:09 UTC, xmonader commented on cmd/deploy.go
> +		ports, err := cmd.Flags().GetUintSlice("ports")
let's make function in `internal/cmd/deploy` with the paramters needed and invoke it here

2023-02-21 17:10 UTC, xmonader commented on cmd/deploy.go
> +			log.Error().Err(err).Msg("failed to load configuration try logging again")
try to login again using gridify login

2023-02-21 17:10 UTC, xmonader commented on cmd/deploy.go
> +		repoURL, err := exec.Command("git", "config", "--get", "remote.origin.url").Output()
we assumed that git exists on the system (should be added as a requirement in the readme too)

2023-02-21 17:11 UTC, xmonader commented on cmd/destroy.go
> +		config, err := config.LoadConfigData()
same as the rest, please make a separate function in e.g internal/cmd/destroy thath as the logic and only invoke it here with the required params

2023-02-21 17:22 UTC, xmonader commented on Makefile
> +build:
please make sure this file is documented in the devdocs

2023-02-21 17:23 UTC, xmonader commented on README.md
> +```
Also please in the dev document make sure to document the workflows e.g https://github.com/threefoldtech/terraform-provider-grid/tree/development/wiki

2023-02-21 17:30 UTC, xmonader requested changes
I added few comments, and also please check if it's possible to use go-git https://github.com/go-git/go-git/ library instead of invoking git binary ourselves

2023-02-22 15:12 UTC, xmonader commented on README.md
> +A tool used to deploy projects using [Threefold grid](https://threefold.io/).
deploy `on` instead of `using`

2023-02-22 15:13 UTC, xmonader commented on internal/cmd/deploy.go
> +		log.Error().Err(err).Msg("failed to load configuration try logging again using gridify login")
try to login again instead of logging

2023-02-22 15:13 UTC, xmonader commented on internal/cmd/destroy.go
> +		log.Error().Err(err).Msg("failed to load configuration try logging again using gridify login")
try to login instead of logging

2023-02-22 15:14 UTC, xmonader commented on internal/cmd/login.go
> +	fmt.Print("Please enter grid network: ")
Please enter grid network (mainnet,testnet):

2023-02-22 15:14 UTC, xmonader commented on internal/cmd/login.go
> +		log.Error().Err(err).Msg("failed to read network")
failed to read grid network

2023-02-22 15:15 UTC, xmonader commented on internal/cmd/login.go
> +		log.Error().Msg("invalid network, must be one of: dev, test, qa and main")
invalid grid network

2023-02-22 15:20 UTC, xmonader approved these changes

2023-02-22 16:21 UTC, AbdelrahmanElawady approved these changes

2023-02-22 16:24 UTC, merged